Allow for packages to be upgraded

diff --git a/stew b/stew
--- a/stew
+++ b/stew
@@ -15,9 +15,15 @@ install()
     export PKGNAME
     export STEWDIR
     chmod +x ./"$PKGNAME".sh > /dev/null 2>&1
-    . "$PKGNAME".sh || ( echo -e "\033[1;34m--> Unable to install \"$PKGNAME\"\033[22;0m" && exit 1 )
-    echo -e "\033[1;32mFinished processing package: \"$PKGNAME\". Please review the terminal output for errors.\033[22;0m"
-    exit 0
+    . "$PKGNAME".sh
+    if ( "$?" -eq 0 )
+    then
+        echo -e "\033[1;32m--> Finished processing package: \"$PKGNAME\".\033[22;0m"
+        exit 0
+    else
+        echo -e "\033[1;31m--> An error occured while processing \"$PKGNAME\".\033[22;0m"
+        exit 1
+    fi
 }
 
 remove()
