Still working on the download system

diff --git a/stew b/stew
--- a/stew
+++ b/stew
@@ -10,16 +10,13 @@ update()
 
 install()
 {
-    if [ "$(curl -s -o /dev/null -w "%{http_code}" http://www.raw.github.com/alebcay/stew/master/Recipes/"$PKGNAME".sh)" != "200" ]
-    then
-        echo -e "\033[1;31m--> No package named \"$PKGNAME\" available through stew\033[22;0m" && exit 1
-    else
-        curl -LkOs http://raw.github.com/alebcay/stew/master/Recipes/"$PKGNAME".sh || return 1
-        export PKGNAME
-        export STEWDIR
-        . ./"$PKGNAME".sh || echo -e "\033[1;34m-->Unable to install \"$PKGNAME\"\033[22;0m"
-    exit 1
-    fi
+    cd Recipes
+    curl -LkOs http://raw.github.com/alebcay/stew/master/Recipes/"$PKGNAME".sh || ( echo -e "\033[1;31m--> \"$PKGNAME\" is unusable or nonexistent\033[22;0m" && exit )
+    export PKGNAME
+    export STEWDIR
+    chmod +x ./"$PKGNAME".sh
+    . ./"$PKGNAME".sh || ( echo -e "\033[1;34m-->Unable to install \"$PKGNAME\"\033[22;0m" && exit 1 )
+    exit 0
 }
 
 remove()
@@ -37,7 +34,7 @@ then
 elif [ "$1" == 'install' ]
 then
     PKGNAME="$2"
-    install || ( echo -e "\033[1;31mThe package \"$PKGNAME\" could not be installed.\033[22;0m" && echo -e "\033[1;31mWe would appreciate it if you submitted an issue report on our GitHub repo.\033[22;0m" && exit 1)
+    install || exit 1
 elif [ "$1" == "remove" ]
 then
     remove
