Fixed issue on abcm2ps

diff --git a/stew b/stew
--- a/stew
+++ b/stew
@@ -28,12 +28,16 @@ install()
 
 remove()
 {
-    [ -d "$STEWDIR"/Bowls/"$PKGNAME" ] || ( echo -e "\033[1;31m\"$PKGNAME\" is not installed on your system or cannot be found.\033[22;0m" && exit 1 )
-    rm -rf "$STEWDIR"/Bowls/"$PKGNAME"/
-    cd Recipes
-    curl -Oks https://raw.github.com/alebcay/stew/master/Recipes/"$PKGNAME".rm.sh || ( echo -e "\033[1;31m-->  \"$PKGNAME\" is unusable or nonexistent\033[22;0m" && exit 1 )
-    chmod +x ./"$PKGNAME".sh
-    ( . ./"$PKGNAME".rm.sh && echo -e "\033[1;32m\"$PKGNAME\" was successfully removed.\033[22;0m" ) || ( echo -e "\033[1;31mNo usable automatic removal instructions are available for \"$PKGNAME\"." && echo -e "You may have to manually uninstall it.\033[22;0m" && exit 1 )
+    if [ -d "$STEWDIR"/Bowls/"$PKGNAME" ]
+    then
+        rm -rf "$STEWDIR"/Bowls/"$PKGNAME"/
+        cd Recipes
+        curl -Oks https://raw.github.com/alebcay/stew/master/Recipes/"$PKGNAME".rm.sh || ( echo -e "\033[1;31m-->  \"$PKGNAME\" is unusable or nonexistent\033[22;0m" && exit 1 )
+        ( . ./"$PKGNAME".rm.sh && echo -e "\033[1;32m\"$PKGNAME\" was successfully removed.\033[22;0m" ) || ( echo -e "\033[1;31mNo usable automatic removal instructions are available for \"$PKGNAME\"." && echo -e "You may have to manually uninstall it.\033[22;0m" && exit 1 )
+    else
+        echo -e "\033[1;31m\"$PKGNAME\" is not installed on your system or cannot be found.\033[22;0m"
+        exit 1
+    fi
 }
 
 clean()
